Repository nextcloud/notifications, pull requests merged in 2018-09, with the labels that each got.

#160 Update config and babel for ie11
  .babelrc.js
  js/notifications.js.map
  package-lock.json
  package.json
Labels: 3. to review, backport-request, bug, enhancement, high

#162 Add vue build test
  .drone.yml
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  tests/vue-build.sh
Labels: 4. to release

#170 Update all NPM
  js/notifications.js.map
  package-lock.json
  package.json
Labels: 3. to review

#161 [stable14] Update config and babel for ie11
  .babelrc.js
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  package.json
Labels: 4. to release

#176 Update NPM packages
  js/notifications.js.map
  package-lock.json
  package.json
Labels: 4. to release
