Repository nextcloud/notifications, pull requests merged in 2018-07, with the labels that each got.

#132 Add hint about enforced language
  lib/Push.php
  tests/Unit/PushTest.php
Labels: 4. to release

#136 Streamline webpack with all other apps
  Makefile
  js-src/webpack.common.js
  js-src/webpack.config.js
  js-src/webpack.dev.js
  js-src/webpack.prod.js
  lib/AppInfo/Application.php
  package-lock.json
  package.json
Labels: 3. to review

#130 Only pull for new messages if the session is allowed to be kept alive
  js-src/app.js
Labels: 3. to review, backport-request, bug, feature: frontend

#139 [stable13] Always push object data
  lib/Push.php
Labels: 3. to review, enhancement, feature: push

#138 [stable13] Only pull for new messages if the session is allowed to be kept alive
  js/app.js
Labels: 3. to review, bug

#140 [stable13] Add prioritization for Talk
  lib/Push.php
Labels: 3. to review, enhancement, feature: push

#145 Move to src/, import and axios
  js-src/app.js
  js-src/components/action.vue
  package-lock.json
  package.json
  src/App.vue
  src/components/action.vue
  src/components/notification.vue
  src/init.js
  src/richObjectStringParser.js
  src/webpack.common.js
  src/webpack.dev.js
  src/webpack.prod.js
Labels: 4. to release, enhancement, feature: frontend

#142 Allow notifiers to know if we prepare push notifications
  lib/Push.php
Labels: 4. to release, enhancement, feature: push

#146 Fix header icon accessibility
  css/styles.scss
  src/App.vue
Labels: 3. to review, bug, design
