Repository nextcloud/notifications, pull requests merged in 2018-10, with the labels that each got.

#188 Add .l10nignore files for compiled assets
  .l10nignore
  Makefile
Labels: 3. to review, backport-request

#186 Switch to compiled handlebars
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  package.json
  src/richObjectStringParser.js
  src/templates/file.handlebars
  src/templates/unkown.handlebars
  src/templates/unkownLink.handlebars
  src/templates/userLocal.handlebars
  src/templates/userRemote.handlebars
  src/webpack.common.js
  src/webpack.dev.js
Labels: 3. to review

#190 Use the rich message when available and instead of trim overlay with a shadow
  css/styles.scss
  js/notifications.js
  js/notifications.js.map
  src/components/notification.vue
  src/richObjectStringParser.js
Labels: 3. to review, enhancement, feature: frontend
