Repository nextcloud/notifications, pull requests merged in 2019-07, with the labels that each got.

#363 Increase size of icon bubble for more visibility
  img/notifications-new-dark.svg
  img/notifications-new.svg
  img/notifications-red-new-dark.svg
  img/notifications-red-new.svg
Labels: 3. to review, design, enhancement

#372 Send browser notifications again
  js/notifications.js
  js/notifications.js.map
  src/components/Notification.vue
Labels: 4. to release, backport-request, bug, feature: frontend, regression

#373 [stable16] Send browser notifications again
  .drone.yml
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  package.json
  src/components/Notification.vue
Labels: 4. to release

#382 Fix notification body text alignment and text contrast
  css/styles.scss
Labels: 3. to review, design

#383 Trim the subject before encrypting the subject
  lib/Push.php
Labels: 3. to review, backport-request, bug, feature: push

#381 Align the notification subject vertically to the icon
  css/styles.scss
Labels: 3. to review, bug, design

#388 Fix mention and actions layout
  css/styles.scss
Labels: 3. to review, bug

#389 Bring back the delete-all button
  css/styles.scss
  js/notifications.js
  js/notifications.js.map
  src/App.vue
Labels: 3. to review, backport-request, bug, feature: frontend

#318 Send a push message when a notification was deleted
  docs/ocs-endpoint-v2.md
  docs/push-v2.md
  js/notifications.js
  js/notifications.js.map
  lib/App.php
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Controller/EndpointController.php
  lib/Handler.php
  lib/Notifier/AdminNotifications.php
  lib/Push.php
  src/components/Action.vue
  tests/Integration/app/appinfo/app.php
  tests/Integration/app/lib/Notifier.php
  tests/Unit/AppInfo/AppTest.php
  tests/Unit/CapabilitiesTest.php
  tests/Unit/Controller/EndpointControllerTest.php
Labels: 3. to review, enhancement, feature: backend, feature: push

#401 [stable16] Delete all button is missing
  css/styles.scss
  js/notifications.js
  js/notifications.js.map
  src/App.vue
Labels: 3. to review, bug, feature: frontend
