Repository nextcloud/notifications, pull requests merged in 2019-08, with the labels that each got.

#409 The token id is an int
  lib/Controller/PushController.php
Labels: 3. to review, bug

#410 Fix travis database tests
  .travis.yml
  js/notifications.js.map
Labels: 4. to release

#414 Also set the subject when the subject is not too long
  lib/Push.php
Labels: 3. to review, backport-request, bug, feature: push, regression
