Repository nextcloud/notifications, pull requests merged in 2019-03, with the labels that each got.

#300 ✨ Nextcloud 16 polishing
  .eslintrc.js
  .gitattributes
  Makefile
  css/styles.scss
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  package.json
  src/App.vue
  src/components/Action.vue
  src/components/Notification.vue
  src/components/action.vue
  src/components/notification.vue
  src/init.js
  src/richObjectStringParser.js
  src/webpack.common.js
  src/webpack.dev.js
  src/webpack.prod.js
Labels: 3. to review, bug, enhancement

#309 Update all NPM
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#311 Fix lodash replacing the global underscore
  js/notifications.js
  js/notifications.js.map
  src/webpack.common.js
Labels: 3. to review, bug, regression

#312 Make the richObjectStringParser a real ES module
  js/notifications.js
  js/notifications.js.map
  src/richObjectStringParser.js
Labels: 3. to review, bug, regression
