Repository nextcloud/notifications, pull requests merged in 2019-01, with the labels that each got.

#243 Update richObjectStringParser.js
  src/richObjectStringParser.js
Labels: 3. to review, bug, feature: frontend, regression

#246 Move to migrations
  appinfo/database.xml
  appinfo/info.xml
  lib/Migration/Version2004Date20190107135757.php
Labels: 3. to review, technical debt

#249 Switch to nextcloud-axios
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  package.json
  src/App.vue
  src/components/action.vue
  src/components/notification.vue
Labels: 3. to review, enhancement

#257 Fix notification documentation to reflect recent changes
  docs/notification-workflow.md
Labels: 3. to review

#261 Unify the HTML encoding handling with other ROS apps
  docs/notification-workflow.md
  js/notifications.js
  js/notifications.js.map
  src/components/notification.vue
  src/richObjectStringParser.js
Labels: 3. to review, bug
