Repository nextcloud/notifications, pull requests merged in 2019-10, with the labels that each got.

#446 Switch to escape-html
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  package.json
  src/Components/Notification.vue
  src/richObjectStringParser.js
Labels: 3. to review, technical debt

#447 Remove lodash
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  package.json
  src/App.vue
  src/richObjectStringParser.js
  src/webpack.common.js
Labels: 4. to release, enhancement

#449 Use OC.config since oc_config is deprecated
  js/notifications.js
  js/notifications.js.map
  src/App.vue
Labels: 3. to review, technical debt

#456 Delete notifications on user deletion
  lib/AppInfo/Application.php
Labels: 3. to review, bug, feature: backend

#460 Fix error with messages without parameters
  js/notifications.js
  js/notifications.js.map
  src/richObjectStringParser.js
Labels: 3. to review, bug, feature: frontend, regression
