Repository nextcloud/notifications, pull requests merged in 2019-12, with the labels that each got.

#494 Fix header icon hover & focus feedback
  css/styles.scss
Labels: 3. to review, backport-request, bug, design, feature: frontend

#496 Fix cutting of multibyte characters
  lib/Push.php
Labels: 3. to review, backport-request, bug, feature: push

#505 Do not send push notifications when nothing was deleted
  lib/Controller/EndpointController.php
  lib/Handler.php
Labels: 3. to review, backport-request, bug, feature: backend, feature: push

#508 Dismiss notifications properly
  lib/Controller/EndpointController.php
  lib/Handler.php
  tests/Unit/HandlerTest.php
Labels: 3. to review, enhancement

#514 Update npm deps
  js/notifications.js
  js/notifications.js.map
  package-lock.json
Labels: 4. to release

#515 Adjust notification wrapper to menu styles
  css/styles.scss
Labels: 3. to review, bug, design
