Repository nextcloud/notifications, pull requests merged in 2020-09, with the labels that each got.

#742 Register via injectFn()
  lib/AppInfo/Application.php
Labels: 3. to review, feature: backend, technical debt

#743 Keep plaintext fallback when no RichText is given
  css/styles.scss
  js/notifications.js
  js/notifications.js.map
  src/Components/Notification.vue
Labels: 3. to review, bug, feature: frontend

#748 Reflect updated JS assets
  .l10nignore
Labels: 3. to review

#751 Share notification data across tabs
  js/notifications-main.js
  js/notifications-main.js.map
  package-lock.json
  package.json
  src/App.vue
  src/Components/Notification.vue
  src/services/BrowserStorage.js
  src/services/notificationsService.js
Labels: 2. developing, technical debt

#755 Update version on master
  .github/workflows/lint.yml
  .travis.yml
  appinfo/info.xml
  package.json
  tests/Integration/app/appinfo/info.xml
  tests/Integration/composer.json
  tests/Integration/composer.lock
  tests/Integration/config/behat.yml
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/run.sh
Labels: 2. developing
