Repository nextcloud/notifications, pull requests merged in 2020-03, with the labels that each got.

#564 Request the permissions for notifications via user interaction
  js/notifications.js
  js/notifications.js.map
  src/App.vue
  src/Components/Notification.vue
Labels: 3. to review, bug, feature: frontend

#581 Fix long messages
  .eslintignore
  .eslintrc.js
  css/styles.scss
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  package.json
  src/App.vue
  src/Components/Action.vue
  src/Components/Notification.vue
  src/Init.js
  src/richObjectStringParser.js
  src/webpack.common.js
  src/webpack.dev.js
  src/webpack.prod.js
Labels: 3. to review, backport-request, bug, feature: frontend

#550 Prevent delete for impersonated users
  lib/Controller/EndpointController.php
Labels: 3. to review, backport-request, bug, feature: backend

#567 Delete unknown devices
  .gitignore
  lib/Push.php
  tests/Unit/AppInfo/RoutesTest.php
  tests/Unit/Controller/EndpointControllerTest.php
  tests/Unit/Notifier/NotifierTest.php
  tests/Unit/PushTest.php
  tests/Unit/phpunit.xml
Labels: 3. to review, enhancement, feature: push, technical debt

#584 [stable18] Fix long message
  .eslintignore
  .eslintrc.js
  css/styles.scss
  package-lock.json
  package.json
  src/App.vue
  src/Components/Action.vue
  src/Components/Notification.vue
  src/Init.js
  src/richObjectStringParser.js
  src/webpack.common.js
  src/webpack.dev.js
  src/webpack.prod.js
Labels: 3. to review, bug, feature: frontend

#602 Fix mocked services
  tests/Unit/AppInfo/AppTest.php
Labels: 3. to review, bug

#604 Fix Notifications aria label
  js/notifications.js
  js/notifications.js.map
  src/App.vue
Labels: 3. to review, backport-request, bug

#608 [stable18] Request the permissions for notifications via user interaction
  js/notifications.js
  js/notifications.js.map
  src/App.vue
  src/Components/Notification.vue
Labels: 3. to review, backport-request, bug, feature: frontend
