Repository nextcloud/notifications, pull requests merged in 2020-01, with the labels that each got.

#528 Do not overwrite height values
  css/styles.scss
Labels: 3. to review, bug

#540 Force line break on long subject text
  css/styles.scss
Labels: 3. to review, backport-request, bug, design

#551 Update screenshot
  docs/admin-notifications.md
  docs/screenshot.png
Labels: 3. to review, bug

#554 Add linting via github actions
  .github/workflows/lint.yml
  composer.json
Labels: 3. to review

#553 Ship own moment so the app is proper stand alone
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  package.json
  src/Components/Notification.vue
Labels: 3. to review

#556 Run assest check on github actions
  .drone.yml
  .github/workflows/nodejs.yml
Labels: 3. to review
