Repository nextcloud/notifications, pull requests merged in 2020-04, with the labels that each got.

#609 Dont fail completely on Internet Explorer
  .babelrc.js
  .eslintrc.js
  babel.config.js
  js/notifications.js
  js/notifications.js.map
  package-lock.json
  package.json
  src/App.vue
Labels: 3. to review, bug

#614 Update github actions
  .github/workflows/dependabot-approve.yml
  .github/workflows/lint.yml
  .github/workflows/node.yml
  .github/workflows/nodejs.yml
  .travis.yml
Labels: 2. developing, 3. to review

#498 Properly log action failure
  js/notifications.js
  js/notifications.js.map
  src/Components/Action.vue
Labels: 3. to review

#624 Fix unit tests after #620
  tests/Unit/Command/GenerateTest.php
  tests/Unit/Notifier/NotifierTest.php
Labels: 4. to release, bug

#625 Set the ETag when requesting notifications
  js/notifications.js
  js/notifications.js.map
  src/App.vue
Labels: 3. to review, bug, feature: frontend

#621 Try to continue notification polling after the browser was closed ove…
  js/notifications.js
  js/notifications.js.map
  package.json
  src/App.vue
Labels: 3. to review, bug, feature: frontend, papercut
