Repository nextcloud/notifications, pull requests merged in 2021-01, with the labels that each got.

#823 Add pslam
  .github/workflows/static-analysis.yml
  composer.json
  composer.lock
  psalm.xml
  tests/psalm-baseline.xml
Labels: 2. developing, technical debt

#835 support using notify_push to get push notifications
  js/notifications-main.js
  js/notifications-main.js.map
  package.json
  src/App.vue
  src/services/notificationsService.js
Labels: 3. to review

#840 Directly mount notifications
  js/notifications-main.js
  js/notifications-main.js.map
  src/main.js
Labels: 3. to review, bug, feature: frontend

#837 move push_notify logic to a js library
  js/notifications-main.js
  js/notifications-main.js.map
  package-lock.json
  package.json
  src/App.vue
  src/services/notificationsService.js
Labels: 3. to review

#845 Cannot unfold plain text notifications
  css/styles.scss
  js/notifications-main.js
  js/notifications-main.js.map
  src/Components/Notification.vue
Labels: 3. to review, backport-request, bug, feature: frontend

#848 Bumb @nextcloud/notify_push from 1.0.0 to 1.0.1
  js/notifications-main.js
  js/notifications-main.js.map
  package-lock.json
  package.json
Labels: 3. to review
