Repository nextcloud/notifications, pull requests merged in 2021-07, with the labels that each got.

#1036 increase the icon size to 20px
  css/styles.scss
Labels: 3. to review, design, enhancement

#1044 Fallback to 500 when no request was made
  js/notifications-main.js
  js/notifications-main.js.map
  src/services/notificationsService.js
Labels: 3. to review, bug, feature: frontend

#1047 Remove timeout of browser notifications
  js/notifications-main.js
  js/notifications-main.js.map
  src/Components/Notification.vue
Labels: 3. to review, backport-request, bug, feature: frontend
