Repository nextcloud/notifications, pull requests merged in 2021-03, with the labels that each got.

#883 Use notification main link if no parameter has a link
  js/notifications-main.js
  js/notifications-main.js.map
  src/Components/Notification.vue
Labels: 3. to review, bug, feature: frontend

#891 Update documentation to the new way
  docs/notification-workflow.md
Labels: 3. to review, bug, technical debt

#902 Fix "exports is not defined" error
  babel.config.js
  js/notifications-main.js
  js/notifications-main.js.map
  package-lock.json
  package.json
Labels: 3. to review, bug

#847 Move unit and integration testing to github action
  .github/workflows/integration.yml
  .github/workflows/oci.yml
  .github/workflows/phpunit.yml
  .travis.yml
  tests/Integration/run.sh
  tests/Unit/PushTest.php
Labels: 3. to review, technical debt

#906 Use phpunit version from vendor/
  .github/workflows/integration.yml
  .github/workflows/phpunit.yml
Labels: 3. to review, bug

#908 Prepend * to document title when tab hidden and new notifications
  js/notifications-main.js
  js/notifications-main.js.map
  src/App.vue
Labels: 4. to release

#909 Only send desktop notifications in one tab
  js/notifications-main.js
  js/notifications-main.js.map
  src/App.vue
  src/Components/Notification.vue
Labels: 3. to review, bug, feature: frontend
