Repository nextcloud/notifications, pull requests merged in 2021-11, with the labels that each got.

#1101 Improve feedback in test-push when device is too old
  lib/Push.php
Labels: bug, 3. to review, feature: push 📲, feature: backend 🛠️

#1111 Update npm and node engines versions
  package.json
Labels: dependencies

#1113 Only run unit tests when relevant
  .github/workflows/integration.yml
  .github/workflows/phpunit.yml
Labels: 4. to release, technical debt
