Repository nextcloud/notifications, pull requests merged in 2021-04, with the labels that each got.

#918 Update notification-workflow.md
  docs/notification-workflow.md
Labels: 4. to release

#928 Fix admin notification api
  appinfo/routes.php
  docs/admin-notifications.md
  lib/Controller/APIController.php
  tests/Integration/features/admin-notification-v2.feature
  tests/Integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, backport-request, bug, feature: admin notifications

#930 Code++
  appinfo/routes.php
  lib/App.php
  lib/Capabilities.php
  lib/Command/Generate.php
  lib/Command/TestPush.php
  lib/Controller/APIController.php
  lib/Controller/EndpointController.php
  lib/Controller/PushController.php
  lib/Exceptions/NotificationNotFoundException.php
  lib/Handler.php
  lib/Listener/UserDeletedListener.php
  lib/Migration/Version2004Date20190107135757.php
  lib/Migration/Version2010Date20210218082811.php
  lib/Notifier/AdminNotifications.php
  lib/Push.php
  tests/Unit/Controller/APIControllerTest.php
  tests/Unit/Controller/EndpointControllerTest.php
  tests/Unit/PushTest.php
Labels: 3. to review, technical debt

#935 Defer deletion-push when rendering or deleting all notifications
  lib/Controller/EndpointController.php
  tests/Unit/Controller/EndpointControllerTest.php
Labels: 3. to review, bug, feature: push

#937 Only push delete-push to devices that also got the notification
  lib/App.php
  lib/Controller/EndpointController.php
  lib/Handler.php
  lib/Push.php
  tests/Unit/PushTest.php
Labels: 3. to review, backport-request, bug, feature: push
