Repository nextcloud/notifications, pull requests merged in 2022-08, with the labels that each got.

#1238 Don't wrap setting in a div
  js/notifications-settings.js
  js/notifications-settings.js.map
  src/views/UserSettings.vue
Labels: 3. to review

#1240 Remove deprecated at matcher from tests
  tests/Unit/PushTest.php
Labels: 3. to review, technical debt

#1244 Update npm and node engines versions
  package.json
Labels: dependencies

#1253 Handle empty list of notifications to delete
  lib/Handler.php
Labels: 3. to review

#1255 Fix background email job for disabled users
  appinfo/info.xml
  lib/MailNotifications.php
  lib/Migration/Version2011Date20220826074907.php
Labels: bug, 4. to release, backport-request, feature: email reminder ✉️

#1256 [stable24] Fix background email job for disabled users
  appinfo/info.xml
  lib/MailNotifications.php
  lib/Migration/Version2011Date20220826074907.php
Labels: bug, 3. to review, feature: email reminder ✉️

#1257 [stable23] Fix background email job for disabled users
  appinfo/info.xml
  lib/MailNotifications.php
  lib/Migration/Version2011Date20220826074907.php
Labels: bug, 3. to review, feature: email reminder ✉️

#1261 Fix duplicate ID on settings page
  js/notifications-settings.js
  js/notifications-settings.js.map
  src/views/UserSettings.vue
Labels: bug, 3. to review, backport-request, feature: frontend 🖌️

#1262 [stable24] Fix duplicate ID on settings page
  js/notifications-settings.js
  js/notifications-settings.js.map
  src/views/UserSettings.vue
Labels: bug, 3. to review, backport-request, feature: frontend 🖌️
