Repository nextcloud/notifications, pull requests merged in 2022-10, with the labels that each got.

#1299 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1298 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1297 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1310 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1309 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1300 Improve debugging of failing emails
  lib/MailNotifications.php
Labels: 3. to review, feature: email reminder ✉️

#1316 Send the subscription key to the Community push proxy
  lib/Push.php
Labels: enhancement, 4. to release, backport-request, feature: push 📲

#1317 Adjust the expected query count
  tests/Integration/base-query-count.txt
Labels: 4. to release, technical debt

#1337 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1331 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#1332 Updating lint-stylelint.yml workflow from template
  .github/workflows/lint-stylelint.yml
Labels: dependencies

#1334 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#1335 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#1336 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1344 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1343 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1352 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1351 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1350 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
