Repository nextcloud/notifications, pull requests merged in 2022-01, with the labels that each got.

#1121 shortenJsonEncodedMultibyte was moved to \OCP\Util for 23.
  lib/Push.php
Labels: 3. to review, technical debt

#1123 Count queries of integration tests
  .github/workflows/integration.yml
  tests/Integration/base-query-count.txt
Labels: 2. developing, technical debt

#1142 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#1146 Move to templated .github actions
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
Labels: 3. to review, technical debt
