Repository nextcloud/notifications, pull requests merged in 2022-11, with the labels that each got.

#1354 Still push notifications of twofactor_nextcloud_notification when in DND
  .github/workflows/integration.yml
  .github/workflows/phpunit.yml
  lib/Push.php
Labels: bug, 3. to review, backport-request, feature: push 📲

#1359 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1358 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1364 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1365 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1366 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1370 Fix unit tests
  lib/Controller/SettingsController.php
  lib/Listener/PostLoginListener.php
  lib/Listener/UserCreatedListener.php
  lib/Settings/Admin.php
  tests/Unit/AppInfo/RoutesTest.php
Labels: bug, 3. to review

#1373 [stable25] Run NPM audit fix
  package-lock.json
Labels: bug, 3. to review

#1372 [stable24] Run NPM audit fix
  package-lock.json
Labels: bug, 3. to review

#1371 [stable23] Run NPM audit fix
  package-lock.json
Labels: bug, 3. to review

#1382 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
