Repository nextcloud/notifications, pull requests merged in 2023-11, with the labels that each got.

#1710 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1715 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1714 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1713 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1716 fix(UI): Fix NcRichText usage
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue-data_image_svg_xml_base64-ab95a3.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue-data_image_svg_xml_base64-ab95a3.js.map
  src/Components/Notification.vue
Labels: enhancement, 3. to review, feature: frontend 🖌️

#1722 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1728 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1727 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1723 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1729 Create update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: 3. to review, backport-request

#1730 chore(assets): Recompile JS
  js/notifications-admin-settings.js
  js/notifications-admin-settings.js.map
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-settings.js
  js/notifications-settings.js.map
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-728d3f78_mjs.js
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-728d3f78_mjs.js.map
Labels: 3. to review
