Repository nextcloud/notifications, pull requests merged in 2023-12, with the labels that each got.

#1739 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1740 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1743 fix(mail): Fix mail handling when force_language is true or false
  lib/MailNotifications.php
Labels: bug, 3. to review, backport-request, feature: email reminder ✉️

#1750 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1747 Bump psalm to level 3
  composer.json
  lib/AppInfo/Application.php
  lib/Controller/PushController.php
  lib/Handler.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/MailNotifications.php
  lib/Migration/Version2010Date20210218082811.php
  lib/Migration/Version2011Date20210930134607.php
  lib/Push.php
  psalm.xml
  tests/Integration/composer.json
  tests/Integration/composer.lock
  tests/Integration/config/behat.yml
  tests/psalm-baseline.xml
Labels: 3. to review, feature: backend 🛠️, technical debt

#1753 fix(push): Allow apps to provide already parsed notifications
  lib/Push.php
Labels: bug, 3. to review, backport-request, performance

#1752 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1751 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1758 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1760 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1761 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
