Repository nextcloud/notifications, pull requests merged in 2023-06, with the labels that each got.

#1569 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  appinfo/info.xml
  tests/Integration/features/bootstrap/FeatureContext.php
Labels: 3. to review, dependencies, automated

#1583 fix(settings): Delete settings when a user is deleted
  lib/Listener/UserDeletedListener.php
  lib/Model/SettingsMapper.php
Labels: bug, 3. to review, backport-request

#1589 fix(CI): Try to wait for the mysql container in case it did not start…
  .github/workflows/phpunit-mysql.yml
Labels: bug, 3. to review, backport-request

#1590 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#1591 [stable27] fix(CI): Delay mysql configuration so we wait for the mysql container…
  .github/workflows/phpunit-mysql.yml
Labels: 3. to review

#1586 [stable26] chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/performance.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  tests/Integration/features/bootstrap/FeatureContext.php
Labels: 3. to review

#1588 [stable25] chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/integration.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/performance.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  composer.json
  tests/Integration/features/bootstrap/FeatureContext.php
Labels: 3. to review

#1587 [stable27] Update target branch of performance.yml
  .github/workflows/performance.yml
Labels: 3. to review

#1579 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1578 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1595 Update PHP extensions list in performance.yml
  .github/workflows/performance.yml
Labels: 3. to review, backport-request

#1592 [stable25] fix(settings): Delete settings when a user is deleted
  lib/Listener/UserDeletedListener.php
  lib/Model/SettingsMapper.php
Labels: bug, 3. to review

#1597 fix(Vue): Replace deprecated NcHeaderMenu property
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.map
  src/NotificationsApp.vue
Labels: bug, 3. to review
