Repository nextcloud/notifications, pull requests merged in 2023-01, with the labels that each got.

#1405 Bump json5 to newer versions
  package-lock.json
Labels: 3. to review

#1407 [stable25] Bump deps to newer versions
  package-lock.json
Labels: 4. to release

#1408 [stable24] Bump deps to newer versions
  package-lock.json
Labels: 4. to release

#1409 [stable23] Bump deps to newer versions
  package-lock.json
Labels: 4. to release

#1412 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1413 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1414 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1415 Document the push flow and why the proxy is nece…
  docs/push-v2.md
Labels: 3. to review, feature: push 📲

#1421 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1428 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1432 Add option for a dummy test notification
  .github/workflows/integration.yml
  lib/Command/Generate.php
  lib/Notifier/AdminNotifications.php
  psalm.xml
  tests/Unit/Command/GenerateTest.php
  tests/Unit/Notifier/NotifierTest.php
  tests/stubs/oc_hooks_emitter.php
Labels: enhancement, 3. to review, technical debt

#1433 Can not comment on pushes anyway
  .github/workflows/performance.yml
Labels: backport-request

#1437 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1436 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1438 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1429 Group delete pushes
  lib/App.php
  lib/Controller/EndpointController.php
  lib/Push.php
Labels: enhancement, 3. to review, feature: push 📲
