Repository nextcloud/notifications, pull requests merged in 2023-10, with the labels that each got.

#1678 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1679 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1682 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1681 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1683 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1684 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1685 chore(CI): Update workflows
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, technical debt

#1689 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1698 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1699 feat(setup): Add a setup message when the rate limit was reached
  lib/AppInfo/Application.php
  lib/Push.php
  lib/Settings/SetupWarningOnRateLimitReached.php
  tests/Unit/PushTest.php
Labels: enhancement, 3. to review, feature: push 📲, feature: backend 🛠️

#1687 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1688 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1708 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1690 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
