Repository nextcloud/notifications, pull requests merged in 2023-09, with the labels that each got.

#1640 Add OpenAPI spec
  .github/workflows/openapi.yml
  .gitignore
  appinfo/routes.php
  composer.json
  composer.lock
  lib/Capabilities.php
  lib/Controller/APIController.php
  lib/Controller/EndpointController.php
  lib/Controller/PushController.php
  lib/Controller/SettingsController.php
  lib/ResponseDefinitions.php
  openapi.json
  psalm.xml
  tests/psalm-baseline.xml
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review

#1656 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1654 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1657 Fix (visually) removing first notification when executing an action
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.map
  src/Components/Action.vue
  src/Components/Notification.vue
Labels: bug, 3. to review, feature: frontend 🖌️

#1662 [stable27] Fix (visually) removing first notification when executing an action
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.map
  src/Components/Action.vue
  src/Components/Notification.vue
Labels: bug, 3. to review, feature: frontend 🖌️

#1663 [stable26] Fix (visually) removing first notification when executing an action
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.map
  src/Components/Action.vue
  src/Components/Notification.vue
Labels: bug, 3. to review, feature: frontend 🖌️

#1673 Fix typo in EndpointController
  lib/Controller/EndpointController.php
  openapi.json
Labels: 3. to review

#1674 [master] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#1676 chore: Bump @nextcloud/vue to v8-beta.7
  js/notifications-admin-settings.js
  js/notifications-admin-settings.js.LICENSE.txt
  js/notifications-admin-settings.js.map
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue-data_image_svg_xml_base64-ab95a3.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue-data_image_svg_xml_base64-ab95a3.js.LICENSE.txt
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue-data_image_svg_xml_base64-ab95a3.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.LICENSE.txt
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.map
  js/notifications-settings.js
  js/notifications-settings.js.LICENSE.txt
  js/notifications-settings.js.map
  js/notifications-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_nextcloud_notify_push_dist_i-1f3b26.js
  js/notifications-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_nextcloud_notify_push_dist_i-1f3b26.js.LICENSE.txt
  js/notifications-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_nextcloud_notify_push_dist_i-30bc25.js
  js/notifications-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_nextcloud_notify_push_dist_i-30bc25.js.LICENSE.txt
  package-lock.json
  package.json
  src/NotificationsApp.vue
  src/views/AdminSettings.vue
  src/views/UserSettings.vue
Labels: 4. to release
