Repository nextcloud/notifications, pull requests merged in 2023-03, with the labels that each got.

#1472 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#1471 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1484 Deduplicate notifications
  composer.lock
  docs/ocs-endpoint-v2.md
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.map
  lib/Controller/EndpointController.php
  lib/Service/ClientService.php
  src/Components/Notification.vue
  tests/Unit/Controller/EndpointControllerTest.php
Labels: enhancement, 3. to review, backport-request, feature: push 📲, feature: backend 🛠️, feature: frontend 🖌️

#1480 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1481 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1491 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1488 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1489 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1492 fix(log): Remove debugging log entries
  lib/Service/ClientService.php
Labels: bug, 3. to review

#1485 [stable26] Deduplicate notifications
  docs/ocs-endpoint-v2.md
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.map
  lib/Controller/EndpointController.php
  lib/Service/ClientService.php
  src/Components/Notification.vue
  tests/Unit/Controller/EndpointControllerTest.php
Labels: enhancement, 2. developing
