Repository nextcloud/notifications, pull requests merged in 2023-08, with the labels that each got.

#1635 [master] Update nextcloud/ocp dependency
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  composer.lock
Labels: 3. to review, dependencies

#1637 fix(fairuse): Adjust website URL
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.map
  src/Components/Notification.vue
  src/NotificationsApp.vue
Labels: 3. to review, backport-request, feature: frontend 🖌️

#1638 fix(CI): Fix nextcloud/ocp package version
  composer.json
  composer.lock
Labels: 3. to review

#1636 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1630 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1642 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1645 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1651 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1650 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
