Repository nextcloud/notifications, pull requests merged in 2023-04, with the labels that each got.

#1497 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1499 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1498 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1500 Add object type as data attr to notification
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.map
  src/Components/Notification.vue
Labels: enhancement, 2. developing, feature: frontend 🖌️

#1506 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1505 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1502 feat(API): Add an endpoint to check for existance of notification ids
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  appinfo/routes.php
  docs/ocs-endpoint-v2.md
  lib/App.php
  lib/AppInfo/Application.php
  lib/BackgroundJob/GenerateUserSettings.php
  lib/BackgroundJob/SendNotificationMails.php
  lib/Capabilities.php
  lib/Command/Generate.php
  lib/Command/TestPush.php
  lib/Controller/APIController.php
  lib/Controller/EndpointController.php
  lib/Controller/PushController.php
  lib/Controller/SettingsController.php
  lib/Exceptions/NotificationNotFoundException.php
  lib/FakeUser.php
  lib/Handler.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Listener/PostLoginListener.php
  lib/Listener/UserCreatedListener.php
  lib/Listener/UserDeletedListener.php
  lib/MailNotifications.php
  lib/Migration/Version2004Date20190107135757.php
  lib/Migration/Version2010Date20210218082811.php
  lib/Migration/Version2010Date20210218082855.php
  lib/Migration/Version2011Date20210930134607.php
  lib/Migration/Version2011Date20220826074907.php
  lib/Model/Settings.php
  lib/Model/SettingsMapper.php
  lib/Notifier/AdminNotifications.php
  lib/Push.php
  lib/Service/ClientService.php
  lib/Settings/Admin.php
  lib/Settings/AdminSection.php
  lib/Settings/Personal.php
  lib/Settings/PersonalSection.php
  tests/Integration/base-query-count.txt
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/exists-notifications-v2.feature
  tests/Unit/AppInfo/RoutesTest.php
  tests/Unit/CapabilitiesTest.php
Labels: enhancement, 2. developing, backport-request, feature: backend 🛠️

#1508 fix(API): Use array_unique to deduplicate
  lib/Controller/EndpointController.php
Labels: bug, 3. to review

#1509 [stable26] feat(API): Add an endpoint to check for existance of notification ids
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  appinfo/routes.php
  docs/ocs-endpoint-v2.md
  lib/App.php
  lib/AppInfo/Application.php
  lib/BackgroundJob/GenerateUserSettings.php
  lib/BackgroundJob/SendNotificationMails.php
  lib/Capabilities.php
  lib/Command/Generate.php
  lib/Command/TestPush.php
  lib/Controller/APIController.php
  lib/Controller/EndpointController.php
  lib/Controller/PushController.php
  lib/Controller/SettingsController.php
  lib/Exceptions/NotificationNotFoundException.php
  lib/FakeUser.php
  lib/Handler.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Listener/PostLoginListener.php
  lib/Listener/UserCreatedListener.php
  lib/Listener/UserDeletedListener.php
  lib/MailNotifications.php
  lib/Migration/Version2004Date20190107135757.php
  lib/Migration/Version2010Date20210218082811.php
  lib/Migration/Version2010Date20210218082855.php
  lib/Migration/Version2011Date20210930134607.php
  lib/Migration/Version2011Date20220826074907.php
  lib/Model/Settings.php
  lib/Model/SettingsMapper.php
  lib/Notifier/AdminNotifications.php
  lib/Push.php
  lib/Service/ClientService.php
  lib/Settings/Admin.php
  lib/Settings/AdminSection.php
  lib/Settings/Personal.php
  lib/Settings/PersonalSection.php
  tests/Integration/base-query-count.txt
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/exists-notifications-v2.feature
  tests/Unit/AppInfo/RoutesTest.php
  tests/Unit/CapabilitiesTest.php
Labels: enhancement, 3. to review, feature: push 📲, feature: backend 🛠️

#1461 Update doc to remove call to setParsedSubject
  docs/notification-workflow.md
  docs/ocs-endpoint-v2.md
Labels: 3. to review

#1524 chore: Add maintainers as codeowners
  .github/CODEOWNERS
Labels: 3. to review

#1522 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1526 [stable26] fix(deps): Update webpack
  js/notifications-admin-settings.js
  js/notifications-admin-settings.js.map
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.map
  js/notifications-settings.js
  js/notifications-settings.js.map
  js/notifications-vendors-node_modules_nextcloud_initial-state_dist_index_esm_js-node_modules_nextcloud_moment_-4efa53.js
  js/notifications-vendors-node_modules_nextcloud_initial-state_dist_index_esm_js-node_modules_nextcloud_moment_-4efa53.js.map
  package-lock.json
Labels: bug, 3. to review, feature: frontend 🖌️

#1533 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1538 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
