Repository nextcloud/notifications, pull requests merged in 2023-05, with the labels that each got.

#1543 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1542 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1541 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1544 fix: Adapt fake user class to server changes
  lib/FakeUser.php
Labels: bug, 3. to review

#1550 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1551 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1561 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1563 fix(CI): Run tests against PHP 8.2
  .github/workflows/phpunit-mysql.yml
Labels: bug, 3. to review, feature: backend 🛠️

#1564 [stable27] fix(CI): Run tests against PHP 8.2
  .github/workflows/phpunit-mysql.yml
Labels: bug, 3. to review, feature: backend 🛠️

#1562 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
