Repository nextcloud/notifications, pull requests merged in 2023-07, with the labels that each got.

#1600 Create pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#1609 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1626 Remove stable24 from dependabot.yml since it's EOL by now
  .github/dependabot.yml
Labels: 3. to review

#1611 [stable27] chore(deps) - bump semver to 6.3.1
  package-lock.json
Labels: security, dependencies, javascript

#1625 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1624 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
