Repository nextcloud/notifications, pull requests merged in 2024-08, with the labels that each got.

#1995 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2001 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2000 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1973 Add rich object support to API
  appinfo/routes.php
  lib/App.php
  lib/Controller/APIController.php
  lib/Notifier/AdminNotifications.php
  lib/ResponseDefinitions.php
  openapi-administration.json
  openapi-full.json
  openapi-push.json
  openapi.json
  tests/Unit/AppInfo/RoutesTest.php
  tests/Unit/Controller/APIControllerTest.php
  vendor-bin/openapi-extractor/composer.lock
Labels: enhancement, 3. to review, feature: admin notifications 🛃

#2011 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2013 chore(deps): Update openapi-extractor to v1.0.0
  openapi-administration.json
  openapi-full.json
  vendor-bin/openapi-extractor/composer.json
  vendor-bin/openapi-extractor/composer.lock
Labels: 3. to review, backport-request, dependencies

#2015 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#2019 feat(cli): Allow to replace and delete CLI notifications
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  appinfo/info.xml
  docs/admin-notifications.md
  lib/Command/Delete.php
  lib/Command/Generate.php
  tests/Integration/features/bootstrap/CommandLineTrait.php
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/cli-notification.feature
  tests/Unit/Command/GenerateTest.php
Labels: enhancement, 3. to review, backport-request, feature: admin notifications 🛃

#2021 chore(deps): audit dependencies
  package-lock.json
Labels: 3. to review, dependencies, javascript
