Repository nextcloud/notifications, pull requests merged in 2024-01, with the labels that each got.

#1772 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1773 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1774 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1763 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1762 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1776 [stable27] fix(deps): Allow composer plugin explicitly
  composer.json
Labels: bug, 3. to review, backport-request, feature: backend 🛠️

#1777 [stable26] fix(deps): Allow composer plugin explicitly
  composer.json
Labels: bug, 3. to review, feature: backend 🛠️

#1780 chore: bump nextcloud/notify_push to 1.1.4
  js/notifications-admin-settings.js
  js/notifications-admin-settings.js.map
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue.js.map
  js/notifications-node_modules_nextcloud_dialogs_dist_chunks_index-c0bccfab_mjs.js
  js/notifications-node_modules_nextcloud_dialogs_dist_chunks_index-c0bccfab_mjs.js.map
  js/notifications-settings.js
  js/notifications-settings.js.map
  js/notifications-vendors-node_modules_core-js_internals_array-iteration_js-node_modules_core-js_internals_arra-a73f12.js
  js/notifications-vendors-node_modules_core-js_internals_array-iteration_js-node_modules_core-js_internals_arra-a73f12.js.map
  js/notifications-vendors-node_modules_nextcloud_auth_dist_index_js-node_modules_nextcloud_vue_dist_Components_-34992c.js
  js/notifications-vendors-node_modules_nextcloud_auth_dist_index_js-node_modules_nextcloud_vue_dist_Components_-34992c.js.LICENSE.txt
  js/notifications-vendors-node_modules_nextcloud_auth_dist_index_js-node_modules_nextcloud_vue_dist_Components_-34992c.js.map
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-0bd54f66_mjs.js
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-0bd54f66_mjs.js.map
  js/notifications-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_nextcloud_notify_push_dist_i-a30382.js
  js/notifications-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_nextcloud_notify_push_dist_i-a30382.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies, javascript

#1779 [stable28] chore: bump nextcloud/notify_push to 1.1.4
  js/notifications-admin-settings.js
  js/notifications-admin-settings.js.map
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue-data_image_svg_xml_base64-ab95a3.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue-data_image_svg_xml_base64-ab95a3.js.map
  js/notifications-node_modules_nextcloud_dialogs_dist_chunks_index-c0bccfab_mjs.js
  js/notifications-node_modules_nextcloud_dialogs_dist_chunks_index-c0bccfab_mjs.js.map
  js/notifications-settings.js
  js/notifications-settings.js.map
  js/notifications-vendors-node_modules_core-js_internals_array-iteration_js-node_modules_core-js_internals_arra-46f851.js
  js/notifications-vendors-node_modules_core-js_internals_array-iteration_js-node_modules_core-js_internals_arra-46f851.js.map
  js/notifications-vendors-node_modules_nextcloud_auth_dist_index_js-node_modules_nextcloud_vue_dist_Components_-304b96.js
  js/notifications-vendors-node_modules_nextcloud_auth_dist_index_js-node_modules_nextcloud_vue_dist_Components_-304b96.js.LICENSE.txt
  js/notifications-vendors-node_modules_nextcloud_auth_dist_index_js-node_modules_nextcloud_vue_dist_Components_-304b96.js.map
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-0bd54f66_mjs.js
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-0bd54f66_mjs.js.map
  js/notifications-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_nextcloud_notify_push_dist_i-4dbea9.js
  js/notifications-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_nextcloud_notify_push_dist_i-4dbea9.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies, javascript

#1787 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1788 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1789 Update npm and node engines versions
  package.json
Labels: dependencies

#1797 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1796 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1805 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
