Repository nextcloud/notifications, pull requests merged in 2024-02, with the labels that each got.

#1807 techdebt(noid): Update nextcloud/coding-standards to 1.2
  composer.json
  composer.lock
  tests/Integration/features/bootstrap/FeatureContext.php
  vendor-bin/openapi-extractor/composer.lock
Labels: enhancement, 3. to review, feature: backend 🛠️, technical debt

#1813 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1814 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1815 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#1816 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1817 [stable28] chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1818 ci(performance): Update performance test to state-of-art
  .github/workflows/performance.yml
  tests/Integration/base-query-count.txt
Labels: 3. to review, performance

#1821 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1824 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1806 feat(db): Add index on device identifier for quicker deletion
  lib/AppInfo/Application.php
  lib/Listener/AddMissingIndicesListener.php
  lib/Migration/Version2010Date20210218082811.php
Labels: enhancement, 3. to review, feature: push 📲, performance

#1828 fix(push): Correctly ignore push tokens that are not valid again
  .github/workflows/phpunit-mysql.yml
  lib/Push.php
  tests/psalm-baseline.xml
Labels: bug, 3. to review, feature: push 📲

#1835 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
