Repository nextcloud/notifications, pull requests merged in 2024-10, with the labels that each got.

#2067 build(reuse): Move license statements closer to the fragments
  .github/dependabot.yml
  .gitignore
  .l10nignore
  REUSE.toml
  tests/Integration/features/admin-notification-v2.feature
  tests/Integration/features/cli-notification.feature
  tests/Integration/features/delete-notifications-v1.feature
  tests/Integration/features/delete-notifications-v2.feature
  tests/Integration/features/exists-notifications-v2.feature
  tests/Integration/features/notifications-content-v1.feature
  tests/Integration/features/notifications-content-v2.feature
  tests/Integration/features/push-registration.feature
  tests/Integration/features/statuscodes-v1.feature
  tests/Integration/features/statuscodes-v2.feature
Labels: 3. to review

#2071 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2073 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2070 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2074 fix(push): Make testing the push server easier
  lib/Push.php
  tests/Unit/PushTest.php
Labels: bug, 3. to review, feature: push 📲

#2080 chore(dev-deps): Bump nextcloud/ocp package
  composer.lock
Labels: 3. to review, dependencies

#2081 [stable30] chore(dev-deps): Bump nextcloud/ocp package
  composer.lock
Labels: 3. to review, dependencies

#2083 [master] Update nextcloud/ocp dependency
  composer.lock
  lib/Model/Settings.php
Labels: 3. to review, dependencies

#2089 docs(push-v2): Document silent delete-multiple push notification
  docs/push-v2.md
Labels: 3. to review
