Repository nextcloud/notifications, pull requests merged in 2024-04, with the labels that each got.

#1875 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1876 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1877 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1879 fix(openapi): Update openapi-extractor
  openapi-full.json
  openapi.json
  vendor-bin/openapi-extractor/composer.lock
Labels: bug, 3. to review, feature: backend 🛠️

#1880 perf(push): Only get user language when needed
  lib/Push.php
Labels: bug, 3. to review, backport-request, feature: push 📲, performance

#1888 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1889 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1890 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1891 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1894 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1896 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#1895 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#1897 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#1905 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1906 chore: Add license headers in missing files
  Makefile
  babel.config.js
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-src_NotificationsApp_vue.js
  js/notifications-src_NotificationsApp_vue.js.map
  src/Components/Action.vue
  src/Components/Notification.vue
  src/NotificationsApp.vue
  src/styles/styles.scss
  stylelint.config.js
  tests/Integration/config/behat.yml
  tests/Integration/run.sh
  tests/stubs/oc_hooks_emitter.php
  tests/vue-build.sh
  webpack.js
Labels: 3. to review
