Repository nextcloud/notifications, pull requests merged in 2024-12, with the labels that each got.

#2111 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2109 feat(push): Add option to send a self-test
  appinfo/routes.php
  composer.json
  lib/Capabilities.php
  lib/Controller/APIController.php
  lib/Notifier/AdminNotifications.php
  lib/Push.php
  openapi-full.json
  openapi-push.json
  tests/Unit/AppInfo/RoutesTest.php
  tests/Unit/CapabilitiesTest.php
  tests/Unit/Controller/APIControllerTest.php
Labels: enhancement, 3. to review, feature: push 📲, feature: backend 🛠️

#2114 chore(i18n): Improved grammar
  lib/Command/TestPush.php
  lib/Controller/APIController.php
Labels: bug, 3. to review

#2113 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2110 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2112 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2116 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2123 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2126 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2129 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
