Repository nextcloud/notifications, pull requests merged in 2024-09, with the labels that each got.

#2025 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2028 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2026 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2034 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2035 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2036 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2041 fix(notifications): Fix notification parameter types
  lib/Notifier/AdminNotifications.php
Labels: bug, 3. to review, backport-request

#2045 docs: Fix ocs endpoint status code documentation
  docs/ocs-endpoint-v2.md
Labels: 3. to review

#2055 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2054 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2057 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2056 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2062 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2063 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2059 feat(priority): Send priority notifications as push during DND
  lib/Push.php
Labels: enhancement, 3. to review, feature: push 📲

#2064 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2065 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
