Repository nextcloud/notifications, pull requests merged in 2024-06, with the labels that each got.

#1936 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1934 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1935 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1933 [stable29] Update nextcloud/ocp dependency
  composer.lock
  tests/psalm-baseline.xml
Labels: 3. to review, dependencies

#1937 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies

#1939 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1940 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1941 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1942 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1943 fix(browser): Don't create web notifications for old notifications
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-src_NotificationsApp_vue.js
  js/notifications-src_NotificationsApp_vue.js.map
  src/Components/Notification.vue
  src/NotificationsApp.vue
Labels: bug, 3. to review, backport-request, feature: frontend 🖌️

#1947 fix: separate creation of browser notifications and sounds from Vue rendering
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-src_NotificationsApp_vue.js
  js/notifications-src_NotificationsApp_vue.js.map
  src/Components/Notification.vue
  src/NotificationsApp.vue
  src/services/webNotificationsService.js
Labels: bug, 3. to review, feature: frontend 🖌️

#1956 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1957 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1961 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1965 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1966 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
