Repository nextcloud/notifications, pull requests merged in 2024-03, with the labels that each got.

#1838 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1840 fix(mail): Use parsed action label in email notification
  lib/MailNotifications.php
Labels: bug, 3. to review, backport-request, feature: email reminder ✉️

#1844 [stable28] chore(deps): audit dependencies
  package-lock.json
Labels: 3. to review, dependencies, javascript

#1845 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1851 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1850 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1849 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1798 feat(push): Try the new Route attribute
  appinfo/routes.php
  lib/Controller/PushController.php
  openapi-full.json
  tests/Unit/AppInfo/RoutesTest.php
  vendor-bin/openapi-extractor/composer.lock
Labels: enhancement, 3. to review, feature: push 📲, feature: backend 🛠️

#1852 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#1856 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1857 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1858 fix(api): Ignore "parsed" link and icon urls when deleting
  lib/Handler.php
Labels: bug, 3. to review, feature: backend 🛠️

#1866 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1872 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
