Repository nextcloud/notifications, pull requests merged in 2024-07, with the labels that each got.

#1968 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#1971 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1969 feat: Adapt FakeUser to new IUser
  lib/FakeUser.php
Labels: 3. to review

#1972 Migrate REUSE to TOML
  .reuse/dep5
  AUTHORS.md
  LICENSES/Apache-2.0.txt
  LICENSES/BSD-2-Clause.txt
  LICENSES/BSD-3-Clause.txt
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/ISC.txt
  LICENSES/MPL-2.0.txt
  README.md
  REUSE.toml
  build-js/WebpackSPDXPlugin.js
  build-js/npm-post-build.sh
  composer.lock
  docs/admin-notifications.md
  docs/notification-workflow.md
  docs/ocs-endpoint-v1.md
  docs/ocs-endpoint-v2.md
  docs/push-v2.md
  docs/screenshot.png.license
  js/notifications-admin-settings.js
  js/notifications-admin-settings.js.LICENSE.txt
  js/notifications-admin-settings.js.license
  js/notifications-admin-settings.js.map
  js/notifications-admin-settings.js.map.license
  js/notifications-main.js
  js/notifications-main.js.LICENSE.txt
  js/notifications-main.js.license
  js/notifications-main.js.map
  js/notifications-main.js.map.license
  js/notifications-node_modules_nextcloud_dialogs_dist_chunks_index-CYiQsZoY_mjs.js.license
  js/notifications-node_modules_nextcloud_dialogs_dist_chunks_index-CYiQsZoY_mjs.js.map.license
  js/notifications-settings.js
  js/notifications-settings.js.LICENSE.txt
  js/notifications-settings.js.license
  js/notifications-settings.js.map
  js/notifications-settings.js.map.license
  js/notifications-src_NotificationsApp_vue.js.license
  js/notifications-src_NotificationsApp_vue.js.map.license
  js/notifications-vendors-node_modules_core-js_modules_es_string_replace_js-node_modules_nextcloud_vue_dist_chu-4924b4.js
  js/notifications-vendors-node_modules_core-js_modules_es_string_replace_js-node_modules_nextcloud_vue_dist_chu-4924b4.js.LICENSE.txt
  js/notifications-vendors-node_modules_core-js_modules_es_string_replace_js-node_modules_nextcloud_vue_dist_chu-4924b4.js.license
  js/notifications-vendors-node_modules_core-js_modules_es_string_replace_js-node_modules_nextcloud_vue_dist_chu-4924b4.js.map
  js/notifications-vendors-node_modules_core-js_modules_es_string_replace_js-node_modules_nextcloud_vue_dist_chu-4924b4.js.map.license
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-DUbP4INd_mjs.js.license
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-DUbP4INd_mjs.js.map.license
  js/notifications-vendors-node_modules_nextcloud_notify_push_dist_index_js-node_modules_howler_dist_howler_js-n-19bbb3.js
  js/notifications-vendors-node_modules_nextcloud_notify_push_dist_index_js-node_modules_howler_dist_howler_js-n-19bbb3.js.LICENSE.txt
  js/notifications-vendors-node_modules_nextcloud_notify_push_dist_index_js-node_modules_howler_dist_howler_js-n-19bbb3.js.license
  js/notifications-vendors-node_modules_nextcloud_notify_push_dist_index_js-node_modules_howler_dist_howler_js-n-19bbb3.js.map
  js/notifications-vendors-node_modules_nextcloud_notify_push_dist_index_js-node_modules_howler_dist_howler_js-n-19bbb3.js.map.license
  package.json
  webpack.js
Labels: 2. developing, technical debt

#1976 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1975 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1982 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1977 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1978 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1974 feat(sounds): play call notification sound on second output device
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-settings.js
  js/notifications-settings.js.license
  js/notifications-settings.js.map
  js/notifications-src_NotificationsApp_vue.js
  js/notifications-src_NotificationsApp_vue.js.map
  package-lock.json
  package.json
  src/services/webNotificationsService.js
  src/views/UserSettings.vue
Labels: enhancement, 3. to review, feature: frontend 🖌️

#1990 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1987 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1988 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1989 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
