Repository nextcloud/notifications, pull requests merged in 2025-06, with the labels that each got.

#2376 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2378 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2375 feat(APIController): Return nid when doing push self-test
  lib/Controller/APIController.php
  openapi-full.json
  openapi-push.json
Labels: enhancement, 3. to review, feature: push 📲

#2383 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2391 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2397 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2400 chore: Update coding-standards to 1.4
  lib/Controller/PushController.php
  vendor-bin/csfixer/composer.json
  vendor-bin/csfixer/composer.lock
Labels: 3. to review

#2401 ci: Adjust performance base with current master
  tests/Integration/base-query-count.txt
  tests/Integration/base-query-list.txt
Labels: 3. to review, performance

#2402 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2410 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2407 fix(router): Remove routes.php
  appinfo/routes.php
  lib/Controller/APIController.php
  lib/Controller/EndpointController.php
  lib/Controller/SettingsController.php
  openapi-full.json
  tests/Unit/AppInfo/ApplicationTest.php
  tests/Unit/AppInfo/RoutesTest.php
Labels: 3. to review
