Repository nextcloud/notifications, pull requests merged in 2025-05, with the labels that each got.

#2326 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2327 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2341 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2350 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2342 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2352 chore(tests): Cleanup bootstrap.php to be forward-compatible
  tests/Unit/bootstrap.php
Labels: 3. to review

#2356 ci: Skip printing the log as we count the queries and upload it already
  .github/workflows/performance.yml
Labels: 3. to review

#2358 ci: Update workflows
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#2362 fix: Align FakeUser with IUser interface again
  .github/workflows/update-nextcloud-ocp.yml
  composer.lock
  lib/FakeUser.php
Labels: bug, 3. to review

#2364 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2365 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2367 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2366 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
