Repository nextcloud/notifications, pull requests merged in 2025-04, with the labels that each got.

#2284 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2282 [master] Update nextcloud/ocp dependency
  composer.json
  composer.lock
  lib/FakeUser.php
Labels: 3. to review, dependencies

#2283 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2291 ci: Fix typo in performance integration test run
  .github/workflows/performance.yml
  tests/Integration/base-query-count.txt
  tests/Integration/base-query-list.txt
Labels: 3. to review, backport-request

#2298 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2296 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2297 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2289 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2300 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2301 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2304 [stable29] ci: Update workflows
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/openapi.yml
  .github/workflows/performance.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#2305 [stable30] ci: Update workflows
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#2315 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2313 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2314 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
