Repository nextcloud/notifications, pull requests merged in 2025-02, with the labels that each got.

#2177 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2178 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2186 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2189 feat(push): Show error when internet connection is disabled in configuration
  lib/Push.php
Labels: backport-request

#2188 refactor: use vars for repeated calls
  lib/MailNotifications.php
Labels: 3. to review

#2185 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2207 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2208 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2206 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2205 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2218 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2219 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2221 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2226 ci(performance): Fix performance test and ease debugging it
  .github/workflows/performance.yml
  REUSE.toml
  tests/Integration/base-query-count.txt
  tests/Integration/base-query-list.txt
Labels: backport-request
