Repository nextcloud/notifications, pull requests merged in 2025-08, with the labels that each got.

#2448 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2455 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2457 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2458 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2450 [master] Fix npm audit
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#2460 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2462 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2464 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2465 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2466 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2469 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2472 build: update node and npm engines versions
  package.json
Labels: dependencies

#2473 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2357 perf: Only apply default settings when user is created or settings are requested
  js/notifications-admin-settings.mjs
  js/notifications-admin-settings.mjs.map
  lib/AppInfo/Application.php
  lib/BackgroundJob/GenerateUserSettings.php
  lib/Controller/SettingsController.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Listener/PostLoginListener.php
  lib/Listener/UserCreatedListener.php
  lib/MailNotifications.php
  lib/Model/Settings.php
  lib/Model/SettingsMapper.php
  lib/Settings/Personal.php
  src/views/AdminSettings.vue
  tests/Integration/base-query-count.txt
  tests/Integration/base-query-list.txt
Labels: 3. to review, performance

#2475 fix: use outline svg icon for notifications
  img/notifications-dark.svg
  img/notifications.svg
Labels: design, 3. to review, feature: frontend 🖌️

#2476 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
