Repository nextcloud/notifications, pull requests merged in 2025-01, with the labels that each got.

#2127 chore(workflow): update workflows
  .github/workflows/block-merge-freeze.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/openapi.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  composer.json
Labels: 3. to review, technical debt

#2142 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2139 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2137 [stable28] Fix npm audit
  js/notifications-admin-settings.js
  js/notifications-admin-settings.js.LICENSE.txt
  js/notifications-admin-settings.js.map
  js/notifications-data_image_svg_xml_3csvg_20xmlns_27http_www_w3_org_2000_svg_27_20width_2724_27_20height_2724_-b2e651.js
  js/notifications-data_image_svg_xml_base64_PCEtLSBUaGlzIGljb24gaXMgcGFydCBvZiBNYXRlcmlhbCBVSSBJY29ucy4gQ29weXJ-e25a52.js
  js/notifications-main.js
  js/notifications-main.js.map
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue-data_image_svg_xml_base64-ab95a3.js
  js/notifications-node_modules_moment_locale_sync_recursive_-src_NotificationsApp_vue-data_image_svg_xml_base64-ab95a3.js.map
  js/notifications-node_modules_nextcloud_dialogs_dist_chunks_index-1zThpkd0_mjs.js
  js/notifications-node_modules_nextcloud_dialogs_dist_chunks_index-1zThpkd0_mjs.js.LICENSE.txt
  js/notifications-node_modules_nextcloud_dialogs_dist_chunks_index-1zThpkd0_mjs.js.map
  js/notifications-node_modules_nextcloud_dialogs_dist_chunks_index-c0bccfab_mjs.js
  js/notifications-node_modules_nextcloud_dialogs_dist_chunks_index-c0bccfab_mjs.js.map
  js/notifications-settings.js
  js/notifications-settings.js.LICENSE.txt
  js/notifications-settings.js.map
  js/notifications-src_NotificationsApp_vue.js
  js/notifications-src_NotificationsApp_vue.js.LICENSE.txt
  js/notifications-src_NotificationsApp_vue.js.map
  js/notifications-vendors-node_modules_nextcloud_auth_dist_index_cjs-node_modules_nextcloud_l10n_dist_index_mjs-eb6d62.js
  js/notifications-vendors-node_modules_nextcloud_auth_dist_index_cjs-node_modules_nextcloud_l10n_dist_index_mjs-eb6d62.js.LICENSE.txt
  js/notifications-vendors-node_modules_nextcloud_auth_dist_index_cjs-node_modules_nextcloud_l10n_dist_index_mjs-eb6d62.js.map
  js/notifications-vendors-node_modules_nextcloud_auth_dist_index_js-node_modules_nextcloud_vue_dist_Components_-304b96.js
  js/notifications-vendors-node_modules_nextcloud_auth_dist_index_js-node_modules_nextcloud_vue_dist_Components_-304b96.js.map
  js/notifications-vendors-node_modules_nextcloud_browser-storage_dist_index_js-node_modules_nextcloud_notify_pu-a2287b.js
  js/notifications-vendors-node_modules_nextcloud_browser-storage_dist_index_js-node_modules_nextcloud_notify_pu-a2287b.js.LICENSE.txt
  js/notifications-vendors-node_modules_nextcloud_browser-storage_dist_index_js-node_modules_nextcloud_notify_pu-a2287b.js.map
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-0bd54f66_mjs.js
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-0bd54f66_mjs.js.map
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-cOp1W5mL_mjs.js
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-cOp1W5mL_mjs.js.LICENSE.txt
  js/notifications-vendors-node_modules_nextcloud_dialogs_dist_chunks_FilePicker-cOp1W5mL_mjs.js.map
  js/notifications-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_nextcloud_notify_push_dist_i-4dbea9.js
  js/notifications-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_nextcloud_notify_push_dist_i-4dbea9.js.map
  package-lock.json
Labels: 3. to review, dependencies

#2140 [master] Update nextcloud/ocp dependency
  composer.lock
  lib/FakeUser.php
Labels: 3. to review, dependencies

#2141 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2154 ci: Update GitHub workflows
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/openapi.yml
  .github/workflows/performance.yml
Labels: 3. to review

#2149 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2151 [stable30] Fix npm audit
  js/BrowserStorage-DJ68uFBL.chunk.mjs.license
  js/BrowserStorage-DJ68uFBL.chunk.mjs.map.license
  js/NotificationsApp-DV09BU4a.chunk.mjs.license
  js/NotificationsApp-DV09BU4a.chunk.mjs.map.license
  js/_plugin-vue2_normalizer-IVCPCvfq.chunk.mjs.license
  js/_plugin-vue2_normalizer-IVCPCvfq.chunk.mjs.map.license
  js/index-DwSndjwp.chunk.mjs.license
  js/index-DwSndjwp.chunk.mjs.map.license
  js/notifications-settings.mjs.license
  js/notifications-settings.mjs.map.license
  package-lock.json
Labels: 3. to review, dependencies

#2169 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2167 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2168 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2166 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2150 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2175 fix(APIController): Allow self-test depending on token and not user-agent
  lib/Controller/APIController.php
Labels: bug, 3. to review, backport-request
