Repository nextcloud/notifications, pull requests merged in 2025-03, with the labels that each got.

#2220 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2233 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2234 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2235 fix(push): Check last activity and last check for age
  lib/Push.php
  tests/Unit/PushTest.php
Labels: bug, 3. to review, backport-request, feature: push 📲

#2225 fix(push): Improve test-push output
  lib/Command/TestPush.php
  lib/Push.php
Labels: enhancement, 3. to review, backport-request, feature: push 📲

#2246 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2247 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2248 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2256 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2261 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2262 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2263 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2260 style: fix custom icon height
  css/main-CLWZwcZO.chunk.css
  css/main-D1MVrAjl.chunk.css
  css/notifications-main.css
  js/NotificationsApp-Dc5n3ZTC.chunk.mjs
  src/styles/styles.scss
Labels: bug, 3. to review, feature: frontend 🖌️

#2273 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2274 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2272 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2275 [stable31] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2276 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
